version: 0.2

env:
  shell: bash
phases:
  install:
    commands:
      - echo "Installing HashiCorp Terraform..."
      - curl -qL -o /tmp/terraform.zip https://releases.hashicorp.com/terraform/0.12.24/terraform_0.12.24_linux_amd64.zip
      - unzip -o /tmp/terraform.zip -d /usr/bin
  pre_build:
    commands:
      - cd app-iac
      - terraform init
      - terraform plan -out infrastructure.plan
artifacts:
  files:
    - ./app-iac/infrastructure.plan
  discard-paths: yes