version: 0.2

env:
  shell: bash
  parameter-store:
    CURRENT_AMI: "/hlugo/terraform-bg/current-ami"
    CURRENT_ENV: "/hlugo/terraform-bg/current-env"
phases:
  install:
    commands:
      - echo "Using blue percent $BLUE_TRAFFIC_PERCENT"
      - echo "Using green percent $GREEN_TRAFFIC_PERCENT"
      - echo "Using green $GREEN_ENV_ENABLED"
      - echo "Current AMI $CURRENT_AMI"
      - echo "Current ENV $CURRENT_ENV"
      - echo "Installing jq..."
      - curl -qL -o /usr/bin/jq https://stedolan.github.io/jq/download/linux64/jq && chmod +x /usr/bin/jq
      - echo "Installing HashiCorp Terraform..."
      - curl -qL -o /tmp/terraform.zip https://releases.hashicorp.com/terraform/0.12.24/terraform_0.12.24_linux_amd64.zip
      - unzip -o /tmp/terraform.zip -d /usr/bin
  build:
    commands:
      - AMI_ID=$(jq '.builds[0].artifact_id' $CODEBUILD_SRC_DIR_BuildArtifacts/manifest.json | cut -d ":" -f2)
      - |
        if [ "$CURRENT_ENV" = "blue_env" ]; then
          echo "Deploying to green"
        else
          echo "Deploying to blue"
        fi
      - cd app-iac
      - terraform init
      - terraform apply -auto-approve