version: 0.2

env:
  shell: bash
  parameter-store:
    CURRENT_AMI: "/hlugo/terraform-bg/current-ami"
    CURRENT_ENV: "/hlugo/terraform-bg/current-env"
phases:
  install:
    commands:
      - echo "Using green $GREEN_ENV_ENABLED"
      - echo "Installing jq..."
      - curl -qL -o /usr/bin/jq https://stedolan.github.io/jq/download/linux64/jq && chmod +x /usr/bin/jq
      - echo "Installing HashiCorp Terraform..."
      - curl -qL -o /tmp/terraform.zip https://releases.hashicorp.com/terraform/0.12.24/terraform_0.12.24_linux_amd64.zip
      - unzip -o /tmp/terraform.zip -d /usr/bin
  build:
    commands:
      - AMI_ID=$(jq -r '.builds[0].artifact_id' $CODEBUILD_SRC_DIR_BuildArtifacts/manifest.json | cut -d ":" -f2)
      - echo "Using AMI $AMI_ID"
      - cd app-iac
      - terraform init
      - |
        if [ "$CURRENT_ENV" = "left_env" ]; then
          echo "Left environment is currently blue"
          terraform apply -auto-approve \
            -var left_env_ami_id="$CURRENT_AMI" \
            -var left_env_routing_weight="$BLUE_TRAFFIC_PERCENT" \
            -var left_env_enabled=1 \
            -var right_env_ami_id="$AMI_ID" \
            -var right_env_routing_weight="$GREEN_TRAFFIC_PERCENT" \
            -var right_env_enabled=1

        else
          echo "Right environment is currently blue"
          terraform apply -auto-approve \
            -var left_env_ami_id="$AMI_ID" \
            -var left_env_routing_weight="$GREEN_TRAFFIC_PERCENT" \
            -var left_env_enabled=1 \
            -var right_env_ami_id="$CURRENT_AMI" \
            -var right_env_routing_weight="$BLUE_TRAFFIC_PERCENT" \
            -var right_env_enabled=1
        fi
      - |
        if [ "$UPDATE_POINTERS" = "1" ]; then
          echo "Updating current AMI"
          aws ssm put-parameter --overwrite --name "/hlugo/terraform-bg/current-ami" --value "$AMI_ID"

          if [ "$CURRENT_ENV" = "left_env" ]; then
            echo "Updating current environment to right_env"
            aws ssm put-parameter --overwrite --name "/hlugo/terraform-bg/current-env" --value "right_env"
          else
            echo "Updating current environment to left_env"
            aws ssm put-parameter --overwrite --name "/hlugo/terraform-bg/current-env" --value "left_env"
          fi
        fi